# Generated by Django 5.2.11 on 2026-02-15 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.socio')),
            ],
        ),
    ]
